/** Dark Mode Attack Simulation Data — Phase 2 */
export interface DarkSimPhase { label: string; icon: string; status: 'pass' | 'warn' | 'fail' }
export interface DarkSimFinding { title: string; severity: 'critical' | 'high' | 'medium' | 'low'; detail: string }
export interface DarkSimulation {
  name: string; desc: string; phases: DarkSimPhase[];
  mitre: string[]; impact: { confidentiality: number; integrity: number; availability: number };
  findings: DarkSimFinding[];
  mockResult: string;
}
export type DarkSimMap = Record<string, Record<string, DarkSimulation>>;

export const DARK_SIMULATIONS: Record<string, Record<string, {
    name: string; desc: string; phases: Array<{ label: string; icon: string; status: 'pass' | 'warn' | 'fail' }>;
    mitre: string[]; impact: { confidentiality: number; integrity: number; availability: number };
    findings: Array<{ title: string; severity: 'critical' | 'high' | 'medium' | 'low'; detail: string }>;
    mockResult: string;
  }>> = {
    'ciso': {
      '合规漏洞挖掘': { name: '合规渗透测试', desc: '模拟审计发现合规漏洞和绕过路径',
        phases: [{ label: '文档审计', icon: '📋', status: 'pass' }, { label: '技术验证', icon: '🔍', status: 'warn' }, { label: '绕过测试', icon: '🔓', status: 'fail' }, { label: '报告生成', icon: '📊', status: 'pass' }],
        mitre: ['TA0040-Impact', 'T1530-Data from Cloud Storage'], impact: { confidentiality: 72, integrity: 65, availability: 30 },
        findings: [{ title: 'GDPR Art.32 加密不足', severity: 'high', detail: '部分 PII 数据传输未使用 TLS 1.3' }, { title: 'DPIA 流程缺失', severity: 'medium', detail: '3 个新处理活动未进行 DPIA 评估' }],
        mockResult: '发现 5 项合规漏洞，2 项高危（加密不足 + DPIA 缺失），建议 30 天内整改' },
      '监管渗透测试': { name: '监管场景模拟', desc: '模拟监管机构审查发现的安全缺口',
        phases: [{ label: '审查准备', icon: '📑', status: 'pass' }, { label: '现场模拟', icon: '🏢', status: 'warn' }, { label: '缺口发现', icon: '⚠️', status: 'fail' }, { label: '整改建议', icon: '🔧', status: 'pass' }],
        mitre: ['T1078-Valid Accounts', 'T1566-Phishing'], impact: { confidentiality: 55, integrity: 80, availability: 45 },
        findings: [{ title: '网安法等级保护差距', severity: 'critical', detail: '等保三级 12 项控制未达标' }, { title: '日志留存不足', severity: 'high', detail: '审计日志仅保留 45 天（要求 180 天）' }],
        mockResult: '等保三级差距 12 项，日志留存不合规，建议 60 天整改计划' },
      '高管攻击模拟': { name: 'BEC/钓鱼模拟', desc: '模拟针对 C-Suite 的定向攻击',
        phases: [{ label: '情报收集', icon: '🕵️', status: 'pass' }, { label: '社工准备', icon: '🎭', status: 'pass' }, { label: '投递诱饵', icon: '🎣', status: 'fail' }, { label: '权限获取', icon: '👑', status: 'warn' }],
        mitre: ['T1566-Phishing', 'T1534-Internal Spearphishing', 'T1526-Cloud Services Discovery'], impact: { confidentiality: 90, integrity: 85, availability: 40 },
        findings: [{ title: 'CFO 钓鱼成功', severity: 'critical', detail: '模拟 CFO 点击恶意链接率 34%' }, { title: 'MFA 绕过可能', severity: 'high', detail: 'SSO 配置存在 session fixation 风险' }],
        mockResult: '高管钓鱼成功率 34%，MFA 绕过风险存在，建议加强高管安全意识培训' },
      '供应链攻击评估': { name: '供应链攻击路径模拟', desc: '评估通过供应链入侵的可能性',
        phases: [{ label: '供应商画像', icon: '🏭', status: 'pass' }, { label: '依赖分析', icon: '🔗', status: 'warn' }, { label: '攻击注入', icon: '💉', status: 'fail' }, { label: '横向扩散', icon: '🔄', status: 'warn' }],
        mitre: ['T1195-Supply Chain Compromise', 'T1199-Trusted Relationship'], impact: { confidentiality: 78, integrity: 92, availability: 60 },
        findings: [{ title: '第三方 SaaS 供应商 ACR', severity: 'critical', detail: '供应商 A 缺乏 SOC2 认证，存在数据泄露风险' }, { title: '开源依赖漏洞', severity: 'high', detail: '12 个 npm 包存在已知 CVE' }],
        mockResult: '发现 2 家高风险供应商，12 个依赖漏洞，建议供应商安全评估 + SBOM 扫描' },
    },
    'security-expert': {
      '渗透测试': { name: '渗透攻击模拟', desc: '模拟完整的渗透测试攻击链',
        phases: [{ label: '侦察', icon: '👁️', status: 'pass' }, { label: '扫描', icon: '📡', status: 'pass' }, { label: '利用', icon: '💥', status: 'fail' }, { label: '后渗透', icon: '🎯', status: 'warn' }, { label: '报告', icon: '📝', status: 'pass' }],
        mitre: ['T1190-Exploit Public-Facing App', 'T1059-Command Scripting', 'T1078-Valid Accounts'], impact: { confidentiality: 85, integrity: 78, availability: 50 },
        findings: [{ title: 'SQL Injection - 用户登录', severity: 'critical', detail: '登录接口存在联合注入，可提取全部用户表' }, { title: 'SSRF - 内网探测', severity: 'high', detail: '文件上传接口可访问内网 169.254.169.254' }],
        mockResult: '发现 1 个 Critical SQLi + 1 个 High SSRF，可获取 DBA 权限 + 云元数据' },
      '红队演练': { name: '红蓝对抗模拟', desc: '模拟 APT 级别的多阶段红队攻击',
        phases: [{ label: '目标分析', icon: '🎯', status: 'pass' }, { label: '初始突破', icon: '🚪', status: 'pass' }, { label: '内网渗透', icon: '🕸️', status: 'fail' }, { label: '权限维持', icon: '🔐', status: 'warn' }, { label: '目标达成', icon: '🏆', status: 'warn' }],
        mitre: ['TA0001-Initial Access', 'TA0008-Lateral Movement', 'TA0009-Collection', 'TA0011-C2'], impact: { confidentiality: 95, integrity: 88, availability: 65 },
        findings: [{ title: '域控沦陷', severity: 'critical', detail: '通过 Kerberoasting 获取 Domain Admin' }, { title: '持久化后门', severity: 'critical', detail: 'Golden Ticket 可维持 10 年访问' }],
        mockResult: '红队 48h 内完成域控沦陷，Golden Ticket 持久化，建议检测 Kerberoasting + PTH' },
      '横向移动': { name: '内网横向移动模拟', desc: '模拟攻击者在内网的横向扩散',
        phases: [{ label: '初始立足', icon: '🏠', status: 'pass' }, { label: '凭据窃取', icon: '🔑', status: 'pass' }, { label: '横向扩散', icon: '➡️', status: 'fail' }, { label: '关键资产', icon: '💎', status: 'warn' }],
        mitre: ['T1021-Remote Services', 'T1550-Use Alternate Auth', 'T1570-Lateral Tool Transfer'], impact: { confidentiality: 80, integrity: 75, availability: 55 },
        findings: [{ title: 'SMB 签名未强制', severity: 'high', detail: '内网 SMB 签名可选，可进行中间人攻击' }, { title: '本地管理员复用', severity: 'critical', detail: '80% 终端使用相同本地管理员密码' }],
        mockResult: '横向移动成功率 78%，本地管理员密码复用是最大风险，建议 LAPS + SMB 签名强制' },
      '漏洞利用': { name: 'CVE 漏洞利用模拟', desc: '模拟已知 CVE 的实际利用过程',
        phases: [{ label: '漏洞识别', icon: '🔍', status: 'pass' }, { label: 'POC 验证', icon: '🧪', status: 'pass' }, { label: '利用执行', icon: '💣', status: 'fail' }, { label: '影响评估', icon: '📏', status: 'warn' }],
        mitre: ['T1190-Exploit Public-Facing App', 'T1068-Exploitation for Privilege Escalation'], impact: { confidentiality: 70, integrity: 82, availability: 60 },
        findings: [{ title: 'CVE-2024-3094 XZ后门', severity: 'critical', detail: 'SSH 服务受影响，可远程代码执行' }, { title: 'CVE-2024-21762 FortiOS', severity: 'high', detail: 'Out-of-bounds write 可 RCE' }],
        mockResult: '3 个 Critical CVE 可利用（XZ后门 + Log4Shell + FortiOS），建议立即补丁' },
    },
    'secuclaw-commander': {
      'APT模拟': { name: 'APT 攻击链模拟', desc: '模拟高级持续性威胁的完整攻击路径',
        phases: [{ label: '侦察', icon: '🔭', status: 'pass' }, { label: '武器化', icon: '⚔️', status: 'pass' }, { label: '投递', icon: '📦', status: 'fail' }, { label: '利用', icon: '💥', status: 'fail' }, { label: '安装', icon: '📥', status: 'warn' }, { label: 'C2', icon: '📡', status: 'warn' }, { label: '目标', icon: '🎯', status: 'warn' }],
        mitre: ['TA0001-Initial Access', 'TA0002-Execution', 'TA0003-Persistence', 'TA0005-Defense Evasion', 'TA0011-C2', 'TA0010-Exfiltration'], impact: { confidentiality: 95, integrity: 90, availability: 70 },
        findings: [{ title: 'APT29 模拟成功', severity: 'critical', detail: 'Cozy Bear TTP 复现，鱼叉钓鱼→Cobalt Strike→域控' }, { title: '驻留 72h 未检测', severity: 'critical', detail: '攻击者驻留 72 小时未触发任何告警' }],
        mockResult: 'APT29 攻击链完整复现，72h 未检测，建议 EDR + NDR + Threat Hunting' },
      '业务中断攻击': { name: '业务中断影响模拟', desc: '模拟 DDoS/Ransomware 对业务的影响',
        phases: [{ label: '攻击准备', icon: '⚙️', status: 'pass' }, { label: '攻击发起', icon: '🔥', status: 'fail' }, { label: '业务影响', icon: '📉', status: 'fail' }, { label: '恢复评估', icon: '🔄', status: 'warn' }],
        mitre: ['T1489-Service Stop', 'T1490-Inhibit System Recovery', 'T1486-Data Encrypted for Impact'], impact: { confidentiality: 30, integrity: 85, availability: 98 },
        findings: [{ title: 'Ransomware 模拟', severity: 'critical', detail: '核心业务系统加密，RTO 预估 72h' }, { title: '财务影响 ¥2.8M/天', severity: 'critical', detail: '按每小时业务量计算直接损失' }],
        mockResult: '勒索场景：核心系统加密，RTO 72h，直接损失 ¥840万，建议离线备份 + 应急预案' },
      '持久化评估': { name: '后门持久化发现', desc: '评估现有安全控制对持久化攻击的检测能力',
        phases: [{ label: '植入模拟', icon: '🦠', status: 'pass' }, { label: '隐藏测试', icon: '👻', status: 'fail' }, { label: '检测评估', icon: '🔬', status: 'warn' }, { label: '清理验证', icon: '🧹', status: 'pass' }],
        mitre: ['T1053-Scheduled Task', 'T1547-Boot Autostart', 'T1136-Create Account', 'T1574-Hijack Execution Flow'], impact: { confidentiality: 60, integrity: 70, availability: 40 },
        findings: [{ title: '计划任务后门', severity: 'high', detail: '创建的计划任务 48h 未被发现' }, { title: '注册表持久化', severity: 'high', detail: 'Run Key 植入绕过 AV 检测' }],
        mockResult: '4 种持久化技术中仅 1 种被检测，建议加强启动项监控 + 行为分析' },
    },
    'security-ops': {
      '攻击路径发现': { name: '内网攻击路径发现', desc: '自动化发现内网中的攻击路径',
        phases: [{ label: '拓扑发现', icon: '🗺️', status: 'pass' }, { label: '路径分析', icon: '🛤️', status: 'warn' }, { label: '风险评级', icon: '⚡', status: 'fail' }, { label: '修复建议', icon: '🛡️', status: 'pass' }],
        mitre: ['T1046-Network Service Discovery', 'T1087-Account Discovery', 'T1082-System Info Discovery'], impact: { confidentiality: 75, integrity: 68, availability: 45 },
        findings: [{ title: 'DMZ→核心数据库路径', severity: 'critical', detail: '3 跳可达核心数据库，仅靠 VLAN 隔离' }, { title: '运维跳板机风险', severity: 'high', detail: '跳板机无 MFA，可横向到所有服务器' }],
        mockResult: '发现 5 条高危攻击路径，最短 3 跳可达核心资产，建议零信任 + 微分段' },
      '内网横向移动': { name: '网络分段有效性测试', desc: '测试网络分段的实际防护能力',
        phases: [{ label: '分段审计', icon: '🔍', status: 'pass' }, { label: '绕过尝试', icon: '🔓', status: 'fail' }, { label: '横向探测', icon: '↔️', status: 'fail' }, { label: '检测评估', icon: '📡', status: 'warn' }],
        mitre: ['T1021-Remote Services', 'T1046-Network Service Discovery', 'T1570-Lateral Tool Transfer'], impact: { confidentiality: 82, integrity: 76, availability: 50 },
        findings: [{ title: 'VLAN 逃逸成功', severity: 'critical', detail: 'VLAN hopping 攻击可跨越生产/办公网段' }, { title: '防火墙规则过宽', severity: 'high', detail: 'DMZ 到内网开放了 22/3389/445 端口' }],
        mockResult: '3 处分段失效（VLAN逃逸 + 防火墙过宽 + 缺乏东西向流量检测），建议微分段' },
    },
    'security-architect': {
      '架构弱点分析': { name: '架构攻击面分析', desc: '从攻击者视角评估架构安全弱点',
        phases: [{ label: '架构审查', icon: '📐', status: 'pass' }, { label: '信任边界', icon: '🧱', status: 'warn' }, { label: '攻击面', icon: '🎯', status: 'fail' }, { label: '修复建议', icon: '🔧', status: 'pass' }],
        mitre: ['T1190-Exploit Public-Facing App', 'T1133-External Remote Services', 'T1078-Valid Accounts'], impact: { confidentiality: 70, integrity: 65, availability: 45 },
        findings: [{ title: 'API Gateway 无限速', severity: 'high', detail: 'API 网关未配置速率限制，可暴力破解' }, { title: '微服务间无 mTLS', severity: 'high', detail: '服务网格未启用双向 TLS 认证' }],
        mockResult: '发现 4 处架构弱点（无 API 限速 + 无 mTLS + 缺乏零信任 + 日志集中化不足）' },
      '信任边界渗透': { name: '零信任边界渗透测试', desc: '验证零信任架构的实际防护效果',
        phases: [{ label: '策略审计', icon: '📜', status: 'pass' }, { label: '横向测试', icon: '↔️', status: 'warn' }, { label: '权限提升', icon: '⬆️', status: 'fail' }, { label: '绕过验证', icon: '🔓', status: 'warn' }],
        mitre: ['T1078-Valid Accounts', 'T1548-Abuse Elevation Control', 'T1550-Use Alternate Auth'], impact: { confidentiality: 72, integrity: 68, availability: 35 },
        findings: [{ title: '服务账号权限过大', severity: 'high', detail: '3 个服务账号具有管理员权限，违反最小权限' }, { title: '信任评估缺失', severity: 'medium', detail: '设备健康状态未纳入访问决策' }],
        mockResult: '零信任成熟度 3.2/5，主要差距：设备信任评估 + 服务账号治理' },
    },
    'privacy-officer': {
      '隐私合规渗透': { name: '隐私合规渗透测试', desc: '测试隐私保护措施的实际有效性',
        phases: [{ label: '合规审计', icon: '📋', status: 'pass' }, { label: '数据追踪', icon: '🔍', status: 'warn' }, { label: '绕过测试', icon: '🔓', status: 'fail' }, { label: '影响评估', icon: '📊', status: 'pass' }],
        mitre: ['T1530-Data from Cloud Storage', 'T1213-Data from Information Repositories'], impact: { confidentiality: 88, integrity: 45, availability: 20 },
        findings: [{ title: 'PII 数据库未加密', severity: 'critical', detail: '用户手机号/身份证号明文存储' }, { title: '数据脱敏不完整', severity: 'high', detail: '测试环境使用生产数据且未脱敏' }],
        mockResult: '发现 3 项隐私违规（PII明文 + 测试环境未脱敏 + 数据保留超期），建议立即整改' },
      '数据流向追踪': { name: '数据流转路径追踪', desc: '追踪敏感数据在系统中的流转路径',
        phases: [{ label: '数据发现', icon: '🔎', status: 'pass' }, { label: '流向映射', icon: '🗺️', status: 'warn' }, { label: '跨境检测', icon: '🌐', status: 'fail' }, { label: '合规评估', icon: '⚖️', status: 'warn' }],
        mitre: ['T1530-Data from Cloud Storage', 'T1041-Exfiltration Over C2 Channel'], impact: { confidentiality: 80, integrity: 40, availability: 25 },
        findings: [{ title: '数据跨境未评估', severity: 'critical', detail: '用户数据通过 CDN 节点传输至境外' }, { title: '数据保留超期', severity: 'high', detail: '已注销用户数据保留超 180 天' }],
        mockResult: '发现 2 条未授权跨境数据流，建议数据本地化 + 跨境安全评估' },
    },
    'business-security-officer': {
      '业务逻辑漏洞挖掘': { name: '业务逻辑漏洞扫描', desc: '从业务逻辑层面发现安全漏洞',
        phases: [{ label: '业务建模', icon: '📐', status: 'pass' }, { label: '逻辑审计', icon: '🔍', status: 'warn' }, { label: '漏洞验证', icon: '🧪', status: 'fail' }, { label: '影响评估', icon: '💰', status: 'pass' }],
        mitre: ['T1190-Exploit Public-Facing App'], impact: { confidentiality: 60, integrity: 85, availability: 55 },
        findings: [{ title: '支付金额篡改', severity: 'critical', detail: '前端传递金额参数未校验，可修改为 0.01 元' }, { title: '越权访问', severity: 'high', detail: 'A/B 测试接口缺乏权限校验' }],
        mockResult: '发现 2 个业务逻辑漏洞（支付篡改 + 越权），直接经济损失风险 ¥500万/年' },
      '业务中断攻击评估': { name: '业务连续性攻击模拟', desc: '评估业务面对各种中断场景的韧性',
        phases: [{ label: '场景设计', icon: '🎭', status: 'pass' }, { label: '攻击模拟', icon: '🔥', status: 'fail' }, { label: '恢复测试', icon: '🔄', status: 'warn' }, { label: '改进建议', icon: '📈', status: 'pass' }],
        mitre: ['T1489-Service Stop', 'T1490-Inhibit System Recovery'], impact: { confidentiality: 20, integrity: 75, availability: 95 },
        findings: [{ title: 'RTO 不达标', severity: 'critical', detail: '核心系统 RTO 目标 4h，实际恢复需 18h' }, { title: '备份未验证', severity: 'high', detail: '最近一次备份恢复测试在 6 个月前' }],
        mockResult: 'RTO 超标 4.5 倍，备份可靠性未验证，建议季度灾备演练' },
    },
    'supply-chain-security': {
      '供应链渗透测试': { name: '供应链攻击链模拟', desc: '模拟通过供应链渗透核心系统的攻击路径',
        phases: [{ label: '供应商分析', icon: '🏭', status: 'pass' }, { label: '依赖映射', icon: '🔗', status: 'warn' }, { label: '攻击注入', icon: '💉', status: 'fail' }, { label: '影响扩散', icon: '💥', status: 'warn' }],
        mitre: ['T1195-Supply Chain Compromise', 'T1199-Trusted Relationship', 'T1134-Access Token Manipulation'], impact: { confidentiality: 82, integrity: 90, availability: 65 },
        findings: [{ title: 'CI/CD 管道投毒', severity: 'critical', detail: '第三方构建插件可注入恶意代码到生产部署' }, { title: 'npm 依赖混淆', severity: 'high', detail: '3 个内部包名可被外部注册同名包替换' }],
        mockResult: 'CI/CD 管道可投毒，3 个依赖混淆风险，建议签名验证 + 私有 Registry' },
      '供应商攻击模拟': { name: '供应商定向攻击', desc: '模拟针对特定供应商的定向攻击',
        phases: [{ label: '目标选定', icon: '🎯', status: 'pass' }, { label: '攻击路径', icon: '🛤️', status: 'warn' }, { label: '漏洞利用', icon: '🔓', status: 'fail' }, { label: '扩散评估', icon: '📊', status: 'pass' }],
        mitre: ['T1195-Supply Chain Compromise', 'T1078-Valid Accounts'], impact: { confidentiality: 75, integrity: 85, availability: 55 },
        findings: [{ title: '供应商 API Key 泄露', severity: 'critical', detail: '供应商 B 的 API Key 在 GitHub 公开仓库暴露' }, { title: 'VPN 凭据复用', severity: 'high', detail: '供应商员工 VPN 密码与社交账号相同' }],
        mockResult: '供应商 B API Key 泄露 + VPN 弱密码，建议供应商安全评估 + 凭据监控' },
    },
  };
