export declare const PERMISSIONS: {
    readonly AUTH_READ: "auth.read";
    readonly AUTH_WRITE: "auth.write";
    readonly ASSETS_READ: "assets.read";
    readonly ASSETS_WRITE: "assets.write";
    readonly ASSETS_DELETE: "assets.delete";
    readonly VULNS_READ: "vulnerabilities.read";
    readonly VULNS_WRITE: "vulnerabilities.write";
    readonly VULNS_DELETE: "vulnerabilities.delete";
    readonly INCIDENTS_READ: "incidents.read";
    readonly INCIDENTS_WRITE: "incidents.write";
    readonly INCIDENTS_DELETE: "incidents.delete";
    readonly THREATS_READ: "threats.read";
    readonly THREATS_WRITE: "threats.write";
    readonly COMPLIANCE_READ: "compliance.read";
    readonly COMPLIANCE_WRITE: "compliance.write";
    readonly CAPABILITIES_READ: "capabilities.read";
    readonly CAPABILITIES_WRITE: "capabilities.write";
    readonly KNOWLEDGE_READ: "knowledge.read";
    readonly AI_READ: "ai.read";
    readonly AI_WRITE: "ai.write";
    readonly LLM_MANAGE: "llm.manage";
    readonly CHANNELS_READ: "channels.read";
    readonly CHANNELS_WRITE: "channels.write";
    readonly COMMANDER_READ: "commander.read";
    readonly COMMANDER_WRITE: "commander.write";
    readonly KPI_READ: "kpi.read";
    readonly ROLES_READ: "roles.read";
    readonly ROLES_WRITE: "roles.write";
    readonly USERS_READ: "users.read";
    readonly USERS_WRITE: "users.write";
    readonly REPORTS_READ: "reports.read";
    readonly REPORTS_WRITE: "reports.write";
    readonly AUDIT_READ: "audit.read";
    readonly SKILLS_READ: "skills.read";
    readonly VENDORS_READ: "vendors.read";
    readonly VENDORS_WRITE: "vendors.write";
    readonly VENDORS_DELETE: "vendors.delete";
    readonly PRIVACY_READ: "privacy.read";
    readonly PRIVACY_WRITE: "privacy.write";
    readonly ALERTS_READ: "alerts.read";
    readonly ALERTS_WRITE: "alerts.write";
    readonly BCM_READ: "bcm.read";
    readonly BCM_WRITE: "bcm.write";
    readonly THREAT_INTEL_READ: "threat-intel.read";
    readonly THREAT_INTEL_WRITE: "threat-intel.write";
    readonly MATURITY_READ: "maturity.read";
    readonly MATURITY_WRITE: "maturity.write";
    readonly BUDGET_READ: "budget.read";
    readonly BUDGET_WRITE: "budget.write";
    readonly REPORTS_BOARD: "reports.board";
    readonly ATTACK_PATH_READ: "attack-path.read";
    readonly ATTACK_PATH_WRITE: "attack-path.write";
};
export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export declare const PERMISSION_MATRIX: Record<string, string[]>;
export declare function getRolePermissions(roleCode: string): string[];
export declare function getInheritedPermissions(roleCode: string): string[];
export declare function hasPermissionWithInheritance(roleCode: string, required: string | string[]): boolean;
export declare function hasAnyPermission(userPermissions: string[], required: string[]): boolean;
export declare function hasAllPermissions(userPermissions: string[], required: string[]): boolean;
//# sourceMappingURL=permissions.d.ts.map